apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-deployment-lb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer                   
